name: Generate Club Data
on:
    push:
        branches:
            - main
jobs:
    generate_club_data:
        name: Update
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Cache Dependencies
              uses: actions/cache@v2
              env:
                  cache-name: node-cache
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-
            - name: Install Dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: Generate Club Data
              run: |
                  mkdir out
                  mkdir out/covers
                  npm run generate-club-data
            - name: 'Release 💾'
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: release
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  FOLDER: out
